In [2]:
import numpy as np

In [3]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [4]:
arr1 + arr2

array([11, 22, 33, 44])

In [5]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [7]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [8]:
arr1 / arr2

array([10., 10., 10., 10.])

In [9]:
arr2 * 2

array([2, 4, 6, 8])

In [10]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
1 / arr2

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [12]:
arr1 > 20

array([False, False,  True,  True])

In [17]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [18]:
[arr.sum(), arr.mean()]

[10, 2.5]

In [19]:
[arr.std(), arr.var()]

[1.118033988749895, 1.25]

In [20]:
[arr.min(), arr.max()]

[1, 4]

In [21]:
arr.cumsum() # cumulative sum 누적합

array([ 1,  3,  6, 10], dtype=int32)

In [22]:
arr.cumprod() # 누적곱

array([ 1,  2,  6, 24], dtype=int32)

In [23]:
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)

In [24]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [25]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [26]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [30]:
np.linalg.inv(A) # linalg: linear algebra

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [31]:
np.linalg.det(A)

-2.0

In [33]:
A * 10 # 이때 A 와 10 은 차원이 다르므로, 10 을 A의 차원에 맞추어 broadcasting 한다.

array([[ 0, 10],
       [20, 30]])

In [35]:
B = np.array([10,20])
A * B # 이때는 [10,20]  이 [[10,20], [10,20]] 으로 broadcasting 됨

array([[ 0, 20],
       [20, 60]])

In [36]:
x = np.array([3.14, -3.1415, 1.4, -2.9, 5.6, 13.36])

In [37]:
x2d = x.reshape(3,2)

In [38]:
x2d

array([[ 3.14  , -3.1415],
       [ 1.4   , -2.9   ],
       [ 5.6   , 13.36  ]])

In [39]:
np.abs(x)

array([ 3.14  ,  3.1415,  1.4   ,  2.9   ,  5.6   , 13.36  ])

In [40]:
np.sqrt(abs(x))

array([1.77200451, 1.77242771, 1.18321596, 1.70293864, 2.36643191,
       3.65513338])

In [41]:
np.log(abs(x))

array([1.1442228 , 1.14470039, 0.33647224, 1.06471074, 1.7227666 ,
       2.59226517])

In [42]:
np.cos(x)

array([-0.99999873, -1.        ,  0.16996714, -0.97095817,  0.77556588,
        0.70126254])

In [45]:
np.modf(x) # 소수와 정수부분으로 나누어 주는 유니버설 함수

(array([ 0.14  , -0.1415,  0.4   , -0.9   ,  0.6   ,  0.36  ]),
 array([ 3., -3.,  1., -2.,  5., 13.]))

In [46]:
np.modf(x)[1] # [0] : 소수 [1] : 정수부분 이므로 지금은 정수부분 출력

array([ 3., -3.,  1., -2.,  5., 13.])

In [51]:
import math
dResult = list(map(lambda t : math.sqrt(abs(t)),x))
print(dResult)

[1.772004514666935, 1.772427713617681, 1.1832159566199232, 1.70293863659264, 2.3664319132398464, 3.655133376499413]


In [55]:
map(float,x)

In [56]:
print(map(float,x))

In [57]:
print(list(map(float,x)))

[3.14, -3.1415, 1.4, -2.9, 5.6, 13.36]


In [62]:
print(list(map(lambda t : math.sqrt(abs(t)), x)))

[1.772004514666935, 1.772427713617681, 1.1832159566199232, 1.70293863659264, 2.3664319132398464, 3.655133376499413]


In [69]:
a1 = np.array([1,2,3,4,6,7])

In [71]:
a1[[1,2,5]]

array([2, 3, 7])

In [72]:
a2 = a1.reshape(2,3)

In [73]:
a2

array([[1, 2, 3],
       [4, 6, 7]])

In [75]:
a2[0,2] # (1,3) 원소 추출

3

In [77]:
a2[1] # 두번째 행 원소 추출

array([4, 6, 7])

In [78]:
a2[1] = np.array([8,9,0])

In [79]:
a2

array([[1, 2, 3],
       [8, 9, 0]])

In [84]:
a2[[0,1,1],[0,1,2]] # 배열명[[행위치1, 행위치2, ..., 행위치n],[열위치1, 열위치2, ..., 열위치n]]

array([1, 9, 0])

In [85]:
a2[a2>4]

array([8, 9])

In [86]:
a2[(a2%2)==0]

array([2, 8, 0])

In [88]:
a2[:1]

array([[1, 2, 3]])

In [89]:
a2[:2]

array([[1, 2, 3],
       [8, 9, 0]])

In [90]:
a2[:,2]

array([3, 0])

In [91]:
a2[:,[1,2]]

array([[2, 3],
       [9, 0]])

In [92]:
a2[:2,1:]

array([[2, 3],
       [9, 0]])

In [94]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [95]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a2[1][2]

6

In [97]:
a2[1][0:2]

array([4, 5])

In [98]:
a2[1, 0:2]

array([4, 5])

In [101]:
a2[:][1:] # a2[:] 는 a2 와 같다. a2 의 모든 행을 뜻하기 때문.

array([[4, 5, 6],
       [7, 8, 9]])

In [104]:
a2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
a2[:, 1:] # 모든 행의 2,3 열 추출

array([[2, 3],
       [5, 6],
       [8, 9]])

# View of ndarray

In [122]:
arr = np.arange(10)
print("arr = ", arr, arr.dtype)
sliced = arr[5:7] # https://studymake.tistory.com/406, https://nuguziii.github.io/dev/dev-001/
print("sliced=", sliced, sliced.dtype, '\n')

sliced[1] = 3.14
print("sliced = ", sliced)
print("arr = ", arr)
sliced[:] = 64
print("arr = ",arr)

sliced = sliced.astype(np.float64)
sliced[0] = 8.14
print("\n형변환 =", sliced)
print('arr = ',arr)


arr = arr.astype(np.float64)
sliced[0] = 8.14
print("\n형변환 =", sliced)
print('arr = ',arr)

arr[5] = 11
print("\n형변환 =", sliced)
print('arr = ',arr)


arr =  [0 1 2 3 4 5 6 7 8 9] int32
sliced= [5 6] int32 

sliced =  [5 3]
arr =  [0 1 2 3 4 5 3 7 8 9]
arr =  [ 0  1  2  3  4 64 64  7  8  9]

형변환 = [ 8.14 64.  ]
arr =  [ 0  1  2  3  4 64 64  7  8  9]

형변환 = [ 8.14 64.  ]
arr =  [ 0.  1.  2.  3.  4. 64. 64.  7.  8.  9.]

형변환 = [ 8.14 64.  ]
arr =  [ 0.  1.  2.  3.  4. 11. 64.  7.  8.  9.]


In [123]:
arr = np.arange(10)
print("arr = ", arr, arr.dtype)
sliced = arr[5:7].copy() # 복사본. 원본을 복사한 값
print("sliced=", sliced, sliced.dtype, '\n')

sliced[1] = 3.14
print("sliced = ", sliced)
print("arr = ", arr)
sliced[:] = 64
print("arr = ",arr)

sliced = sliced.astype(np.float64)
sliced[0] = 8.14
print("\n형변환 =", sliced)
print('arr = ',arr)

arr.astype(np.float64)
sliced[0] = 8.14
print("\n형변환 =", sliced)
print('arr = ',arr)

arr[5] = 11
print("\n형변환 =", sliced)
print('arr = ',arr)


arr =  [0 1 2 3 4 5 6 7 8 9] int32
sliced= [5 6] int32 

sliced =  [5 3]
arr =  [0 1 2 3 4 5 6 7 8 9]
arr =  [0 1 2 3 4 5 6 7 8 9]

형변환 = [ 8.14 64.  ]
arr =  [0 1 2 3 4 5 6 7 8 9]

형변환 = [ 8.14 64.  ]
arr =  [0 1 2 3 4 5 6 7 8 9]

형변환 = [ 8.14 64.  ]
arr =  [ 0  1  2  3  4 11  6  7  8  9]


np.array의 view 는 dimension 속성은 공유하지 않으면서 원소 데이터는 공유함.

In [141]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
new = arr.view()
new = new.reshape(4,2)
print(arr)
print(new, '\n')

new[0,1] = 111
print(arr)
print(new)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[  1 111   3   4]
 [  5   6   7   8]]
[[  1 111]
 [  3   4]
 [  5   6]
 [  7   8]]
