# Array : 순서가 있는 '같은 종류'의 데이터가 저장된 집합

In [1]:
import numpy as np

In [2]:
data1 = [0,1,3]
a1 = np.array(data1)
print(a1)

[0 1 3]


In [3]:
a1

array([0, 1, 3])

In [8]:
a1.dtype # int 는 4바이트 * 8비트 = 32비트

dtype('int32')

In [5]:
data2 = [0.1,3.2]
a2 = np.array(data2)

In [6]:
a2

array([0.1, 3.2])

In [7]:
a2.dtype

dtype('float64')

In [10]:
# 2차원 배열
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#3차원 배열
np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[5,6,7],[8,9,0]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]]])

arr_obj = np.arange(start, stop, step) => 간격을 몇으로 할 것인가?

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

arr_obj = np.linspace(start, stop, num) => 몇개로 나눌것인가?

In [18]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [19]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [21]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a.reshape(4,3) # 가공한 결과를 return 함. a 자체가 바뀌는것이 아님.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
b = a.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
c = a.reshape(2,2,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
print(b.shape)
print(c.shape)

(4, 3)
(2, 2, 3)


In [38]:
print(b.ndim)
print(c.ndim)

2
3


In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [43]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.empty((4,4))

array([[ 6.23042070e-307,  4.67296746e-307,  1.69121096e-306,
        -7.20921271e-017],
       [ 1.42418987e-306,  1.37961641e-306,  1.60220528e-306,
         1.24611266e-306],
       [ 9.34598925e-307,  1.24612081e-306,  1.11260755e-306,
         1.60220393e-306],
       [ 1.51320640e-306,  9.34609790e-307,  1.24610723e-306,
         1.24610723e-306]])

In [48]:
np.random.rand() # 0이상 1미만의 난수

0.9819490855692989

In [49]:
np.random.rand(2,3)

array([[0.77202563, 0.95374165, 0.71011782],
       [0.95447795, 0.69944432, 0.59508079]])

In [54]:
np.random.randint(1,20, size=(2,2)) # randint(low, high, size)

array([[12,  7],
       [19, 13]])

In [56]:
np.random.randint(10) # 0과 10 사이의 난수

2

In [57]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr1

array([1., 2., 3.])

In [61]:
arr2 = np.array(['10','asd'])
arr2.dtype # 출력값 분석: 데이터 형식이 유니코드이며 문자의 수는 최대 3개라는 뜻.

dtype('<U3')

In [62]:
arr = np.array([1,2,3])

In [63]:
arr.dtype

dtype('int32')

In [64]:
float_arr = arr.astype(np.float64)

In [65]:
float_arr.dtype

dtype('float64')

In [66]:
float_arr

array([1., 2., 3.])

In [67]:
arr = np.array([1.4, -0.6])

In [68]:
arr2 = arr.astype(np.int32) # 소수점 아래자리 버림

In [69]:
arr2 

array([1, 0])

In [70]:
arr2.dtype

dtype('int32')